### ISSUE TITLE
icon 

### ISSUE THREAD

**Issue by aji-ptn** [MoilOrg/MoilApp#2]
![image](https://user-images.githubusercontent.com/58238736/122706548-c8bbc200-d28a-11eb-9c3c-45ae21059471.png)

- image center view has no icon

**Comment by aji-ptn** [comment]
change dialog name 

![image](https://user-images.githubusercontent.com/58238736/122717268-f3634600-d29d-11eb-90dd-5e27ddd23443.png)

**Comment by anto112** [comment]
solved.
