### ISSUE TITLE
multiple-view

### ISSUE THREAD

**Issue by aji-ptn** [MoilOrg/MoilApp#4]
![image](https://user-images.githubusercontent.com/58238736/122720637-4fc86480-d2a2-11eb-85fe-d84079e9c075.png)

- plugin name from MainWidows  into multiple view
- give number of every view in multiple view (1. left view 2. middle view. etc) and same as button view number
- direction I suggest button better than down and center for middle view
- same like moilapp, show image source and name when load image from directory.

**Comment by anto112** [comment]
solved.
